### ISSUE TITLE
The text boxes overlap with other texts and points and they are surprisingly far from the point.

### ISSUE THREAD

**Issue by Paeti** [Phlya/adjustText#94] opened 2020-05-31 10:48 UTC
I am currently working on a plot where I compare different graphs. They show evaluation results of ml models for different metrics and difficulty levels.
i use plt.text to mark the respective high points.
As you can see in the picture below this works in principle. unfortunately the boxes overlap. I have already tried the parameters of the adjust_text method, but haven't found any values where it works as desired.

I also checked if the points/boxes where it happens are similar. At first I thought that it happens with texts that have the same x and y coordinates, but this is not the case.

I interpolated the graphs like in your example for subplots and created 1000 virtual points per graph.
I have also played around with this number and 1000 gave the best results.
I had also plotted the virtual points visibly to check if they are wrong and cause the shifting, but they are exactly on the graphs.

Do you have an idea what the wrong arrangement could be, or which adjust_text parameter I would have to change?

If you like, I can also send you the source code of my plot method.

It would be very nice if you could help me!
Thanks a lot! 

![comparison](https://user-images.githubusercontent.com/24375711/83350498-c82d5200-a33c-11ea-9427-a7a0a6feda58.png)

**Comment by Phlya** [comment] 2020-05-31 11:10
Hi, it does look like something strange is going on with some plots, I'd
appreciate a minimal reproducible example to have a look!

**Comment by Paeti** [comment] 2020-05-31 13:38
Hello, it is unfortunately a bit complicated because it is a slightly bigger project and it is a method of a class and uses the instance attributes of the class and its functions. I have rewritten the method to work on its own, but the input format is not 100% the same because of the missing method that loads and preprocesses the data from a txt file.

nevertheless i think you can see what the method should do. On the picture you can also see that the textboxes overlap and are very far away in the corners etc.

Here the code:

import matplotlib.pyplot as plt
import numpy as np
from scipy import interpolate
from adjustText import adjust_text

modus = ["easy", "hard"]
tasks_and_metrics = ["metric1", "metric2"]
number_of_ckpt = 12

model_data_list = \
[
    [                  # model one
        
            [              # data per task
                [          # data per mode
                    np.array([0, 2, 14, 21, 36, 41, 57, 68, 69, 82, 87, 93, 91])
                ], 
                [          # data per mode
                    np.array([0, 5, 17, 19, 34, 43, 49, 70, 65, 71, 85, 91, 95])
                ]
            ], 
            [              # data per task
                [          # data per mode
                    np.array([0, 2, 14, 21, 36, 41, 57, 68, 69, 82, 87, 93, 91])
                ], 
                [          # data per mode
                    np.array([0, 5, 17, 19, 34, 43, 49, 70, 65, 71, 85, 91, 95])
                ]
            ]
        
    ], 
    [                          # model two
        
            [                  # data per task
                [              # data per mode
                    np.array([0, 10, 13, 24, 45, 56, 70, 83, 94, 81, 73, 71, 80])
                ], 
                [              # data per mode
                    np.array([0, 0, 13, 27, 35, 39, 52, 56, 61, 80, 74, 81, 70])
                ]
            ], 
            [                  # data per task
                [              # data per mode
                    np.array([0, 20, 14, 11, 63, 41, 55, 81, 93, 82, 84, 63, 11])
                ], 
                [              # data per mode
                    np.array([0, 7, 19, 19, 18, 43, 41, 77, 65, 75, 85, 90, 97])
                ]
            ]
        
    ]
]

    
def plot_tasks_and_metrics(model_data_list):
        """

        """

        custom_ylim = (0, 101)
        custom_xlim = (0, number_of_ckpt) 
        custom_yticks = range(0, 101, 5)

        fig, axs = plt.subplots(2, 2, figsize=(20, 30))

        plt.setp(axs, xlim=custom_xlim, ylim=custom_ylim,
                 yticks=custom_yticks)                          

        for ax, modus_val in zip(axs[0], modus):
            ax.set_title(modus_val, {'fontsize': 20})  

        for ax, tasks_and_metrics_val in zip(
                axs[:, 0], 
                tasks_and_metrics                                
        ):
            ax.yaxis.label.set_size(20)                          
            ax.set_ylabel(                                       
                tasks_and_metrics_val, rotation=90               
            )

        fig.tight_layout()                                       

        texts = []

        for text_task in range(0, 2):
            text_task_mode_list = []

            for text_mode in range(0, 2):
                text_task_mode_list.append(([], [], []))

            texts.append(text_task_mode_list)

        colors = plt.rcParams['axes.prop_cycle'].by_key()['color']
        xvalues = range(0, number_of_ckpt + 1)
        
        for model_index, model in enumerate(model_data_list):
            print(len(model_data_list))
            print(model)
            for x in range(0, 2):
                for y in range(0, 2):
                    axs[x, y].yaxis.tick_right()             
                    
                    yvalues = model[x][y][0]
                    
                    yvalues_list = list(yvalues)

                    ymax = max(yvalues_list)
                    xmax = yvalues_list.index(ymax)

                    high_point_text = plt.text(
                        xmax,
                        ymax,
                        "max value: " + str(round(ymax, 2)) +
                        "\ncheckpoint: " + str(xmax),
                        {"backgroundcolor": colors[model_index],
                         "fontsize": "x-small"}
                    )

                    texts[x][y][0].append(high_point_text)

                    interpolated_func = interpolate.interp1d(
                        xvalues,
                        yvalues
                    )

                    virtual_points_xvalues = np.linspace(
                        min(xvalues),
                        max(xvalues),
                        1000
                    )
                    virtual_points_yvalues = interpolated_func(
                        virtual_points_xvalues
                    )

                    texts[x][y][1].extend(virtual_points_xvalues)
                    texts[x][y][2].extend(virtual_points_yvalues)

                    axs[x, y].plot(                 
                        xvalues,
                        yvalues_list,
                        color=colors[model_index]
                    )

        for task_index, text_task in enumerate(texts):
            for mode_index, text_mode in enumerate(text_task):
                adjust_text(
                    text_mode[0],
                    text_mode[1],
                    text_mode[2],
                    ax=axs[task_index, mode_index],
                    arrowprops=dict(arrowstyle="->", color="black", lw=0.5)
                )
![simpler_example](https://user-images.githubusercontent.com/24375711/83353702-b9eb3000-a354-11ea-82b3-41c873b82e9d.png)

                
plot_tasks_and_metrics(model_data_list)

**Comment by Phlya** [comment] 2020-05-31 15:13
This looks like a reproducible example, but very non-minimal! Would it be possible to shrink it down to just one plot, and with a simpler code structure?

**Comment by Phlya** [comment] 2020-05-31 15:15
Sorry to be a pain, but the process of excluding complexity might also reveal where an issue is coming from, in case it is some interaction of adjust_text with specific combination of factors.

**Comment by Paeti** [comment] 2020-05-31 16:18
No problem, I can understand that.
I made it simpler again and created a single plot.
The textboxes still overlap and lie over the plots. They are not so far away from the points, but I have to say that in the process of simplifying I didn't know what the problem was.
I don't even know if the changes have improved it or something else.

The code:

```python
import matplotlib.pyplot as plt
import numpy as np
from scipy import interpolate
from adjustText import adjust_text

             
yvalues_1 = np.array([0, 7, 19, 19, 18, 43, 41, 77, 65, 75, 85, 90, 97])
yvalues_2 = np.array([0, 10, 13, 24, 45, 56, 70, 83, 94, 81, 73, 71, 80])
yvalues_3 =np.array([0, 20, 14, 11, 63, 41, 55, 81, 93, 82, 84, 63, 11])

    
def plot_tasks_and_metrics(yvalues_1, yvalues_2, yvalues_3):
    custom_ylim = (0, 101)
    custom_xlim = (0, number_of_ckpt) 
    custom_yticks = range(0, 101, 5)

    fig, ax = plt.subplots()

    plt.setp(ax, xlim=custom_xlim, ylim=custom_ylim,
        yticks=custom_yticks)                          

    fig.tight_layout()                                       

    colors = plt.rcParams['axes.prop_cycle'].by_key()['color']
    xvalues = range(0, number_of_ckpt + 1)
       
    ax.yaxis.tick_right()             
                    
    yvalues_list_1 = yvalues_1.tolist()
    yvalues_list_2 = yvalues_2.tolist()
    yvalues_list_3 = yvalues_3.tolist()

    ymax_1 = max(yvalues_list_1)
    xmax_1 = yvalues_list_1.index(ymax_1)

    ymax_2 = max(yvalues_list_2)
    xmax_2 = yvalues_list_2.index(ymax_2)
    
    ymax_3 = max(yvalues_list_3)
    xmax_3 = yvalues_list_3.index(ymax_3)

    
    high_point_text_1 = plt.text(
        xmax_1,
        ymax_1,
        "max value: " + str(ymax_1) +
        "\ncheckpoint: " + str(xmax_1),
        {"backgroundcolor": colors[0],
        "fontsize": "x-small"}
    )
    
    high_point_text_2 = plt.text(
        xmax_2,
        ymax_2,
        "max value: " + str(ymax_2) +
        "\ncheckpoint: " + str(xmax_2),
        {"backgroundcolor": colors[1],
        "fontsize": "x-small"}
    )
    
    high_point_text_3 = plt.text(
        xmax_3,
        ymax_3,
        "max value: " + str(ymax_3) +
        "\ncheckpoint: " + str(xmax_3),
        {"backgroundcolor": colors[2],
        "fontsize": "x-small"}
    )

                   
    interpolated_func_1 = interpolate.interp1d(
        xvalues,
        yvalues_list_1
    )

    virtual_points_xvalues = np.linspace(
        min(xvalues),
        max(xvalues),
        1000
    )
    virtual_points_yvalues_1 = interpolated_func_1(
        virtual_points_xvalues
    )
    
    interpolated_func_2 = interpolate.interp1d(
        xvalues,
        yvalues_list_2
    )

    virtual_points_yvalues_2 = interpolated_func_2(
        virtual_points_xvalues
    )
    
    interpolated_func_3 = interpolate.interp1d(
        xvalues,
        yvalues_list_3
    )

    virtual_points_yvalues_3 = interpolated_func_3(
        virtual_points_xvalues
    )

    ax.plot(                 
        xvalues,
        yvalues_list_1,    
        color=colors[0]
    )
    
    ax.plot(                 
        xvalues,
        yvalues_list_2,    
        color=colors[1]
    )
    
    ax.plot(                 
        xvalues,
        yvalues_list_3,    
        color=colors[2]
    )
    
    adjust_text(
        [high_point_text_1, high_point_text_2],
        [*xvalues, *xvalues],
        [*yvalues_list_1, *yvalues_list_2],
        arrowprops=dict(arrowstyle="->", color="black", lw=0.5)
    )
                
plot_tasks_and_metrics(yvalues_1, yvalues_2, yvalues_3)

```

![simpler_example](https://user-images.githubusercontent.com/24375711/83357173-15281d00-a36b-11ea-8abc-0e10eb2ec371.png)

**Comment by Phlya** [comment] 2020-05-31 16:47
This example is fixed by including all three texts in the adjust_text function...
```python
...
    adjust_text(
        [high_point_text_1, high_point_text_2, high_point_text_3],
        [*xvalues, *xvalues, *xvalues],
        [*yvalues_list_1, *yvalues_list_2, *yvalues_list_3],
        arrowprops=dict(arrowstyle="->", color="black", lw=0.5)
    )
...
```

![image](https://user-images.githubusercontent.com/2895034/83357816-acd73c80-a366-11ea-8bf1-3245ed3c5bb8.png)

**Comment by Paeti** [comment] 2020-06-01 08:31
Oh, right, I guess that was my fault.
That's right, you add that one, it works.
After you pointed out the error I looked at my more complicated code again, but I didn't find an error anywhere. I do the same with the for loop as I wrote down 3 times in the example.

I checked that the passed axes were really axes and the right ones, i got the virtual dots and texts output and they all had the right type and values to expect.

Do you have an idea in which direction the problem could lie?

**Comment by Phlya** [comment] 2020-06-01 08:40
What if you simplify your original code for the plotting, like don't add any interpolated points, and don't repel text from data points either?

**Comment by Phlya** [comment] 2020-06-01 08:42
Interpolated points can help if you really need to show all the data, but it's a slightly hacky solution which is not entirely predictable...

**Comment by Paeti** [comment] 2020-06-01 09:40
I tried a little more and observed something strange. The return value of adjust_text is the number of iterations.
I took a look at it. With the single plot I get 74 iterations as return value.
The example with the four subplots returns 1, 1, 46, 1 as iterations. I tried it with and without the interpolated functions and got the same values both times.

**Comment by Phlya** [comment] 2020-06-01 09:49
OK, that indeed shows something strange is going on! Does the single plot correspond to one of those used in the script with subplots?
In the second figure you shared here it does look like something is wrong with the axes setup for the first to plots - this is what can lead to all texts clumped together in a corner and some strange behavior... Really need to reproduce it with minimal complexity to figure it out.

**Comment by Phlya** [comment] 2020-06-01 09:52
Wow just saw your edit - don't expand so much!

**Comment by Paeti** [comment] 2020-06-01 10:11
I had also considered whether it has to do with the axes, but I had the axes objects printen and they look right.
I once changed the expand on the single and the subplots everywhere to 1.5.

subplots:
```python

for task_index, text_task in enumerate(texts):
            for mode_index, text_mode in enumerate(text_task):
                test = adjust_text(
                           text_mode[0],
                           text_mode[1],
                           text_mode[2],
                           ax=axs[task_index, mode_index],
                           force_points=.4, 
                           force_text=.35,
                           expand_points=(1.5, 1.5), 
                           expand_text=(1.5, 1.5),
                           arrowprops=dict(arrowstyle="-|>", color="black", lw=0.5)
                        )
                print(axs[task_index, mode_index])
                print(test)

```

single plot:
```python
adjust_iterations = adjust_text(
        [high_point_text_1, high_point_text_2, high_point_text_3],
        [*xvalues, *xvalues, *xvalues],
        [*yvalues_list_1, *yvalues_list_2, *yvalues_list_3],
        force_points=.4, 
        force_text=.35,
        expand_points=(1.5, 1.5), 
        expand_text=(1.5, 1.5),
        arrowprops=dict(arrowstyle="-|>", color="black", lw=0.5)
    )
    
    print(adjust_iterations)

```

new output on the single plot:

25

![simpler_example](https://user-images.githubusercontent.com/24375711/83398842-6f26f200-a400-11ea-87d7-1bb386328893.png)


at the subplot i added a line "print(axs[task_index, mode_index])" above the line "print(test)".
output : 

AxesSubplot(0.125,0.536818;0.352273x0.343182)
1
AxesSubplot(0.547727,0.536818;0.352273x0.343182)
1
AxesSubplot(0.125,0.125;0.352273x0.343182)
11
AxesSubplot(0.547727,0.125;0.352273x0.343182)
2

![subplot_matrix_example](https://user-images.githubusercontent.com/24375711/83399123-f4120b80-a400-11ea-989a-c47391d82ba2.png)

**Comment by Phlya** [comment] 2020-06-01 10:14
What I meant about the axes, is more about their dimensions - i.e. that all xlim/ylim are set correctly and rendedred... Since you are doing adjust_text after all plotting etc it's unlikely to be an issue though!

**Comment by Phlya** [comment] 2020-06-24 08:59
Could you check this with the latest version from github please?

**Closed** 2024-03-18 20:55 UTC

**Comment by jeqcho** [comment] 2025-05-08 21:37
I also had a problem with the text labels overlapping with each other and the points, but moving the code for `adjust_text` to after `ax.xlim` and `ax.ylim` solved it.
