### ISSUE TITLE
Handle a negative log plot?

### ISSUE THREAD

**Issue by MikeDacre** [Phlya/adjustText#25] opened 2017-04-01 06:57 UTC
When trying to plot a negative log plot, and adding labels to the most divergent points, I end up with the following:

![image](https://cloud.githubusercontent.com/assets/77714/24576129/e388c5f0-166a-11e7-8296-76d0ce945eb9.png)

If I now call `adjust_text` after setting the inverted loglog axes, I get this:

![image](https://cloud.githubusercontent.com/assets/77714/24576366/acb97ea2-166f-11e7-805f-cdc8f21692b1.png)

If I set the labels before computing any points, I get this:

![image](https://cloud.githubusercontent.com/assets/77714/24576111/a9ecd5e8-166a-11e7-9797-b7b2727519a8.png)

Code is here: https://github.com/MikeDacre/mike_tools/blob/test_plot/python/plots.py

Line 110 in `scatter` is where I am calling `adust_text` in the second figure above. I move lines 105–111 up to line 52 to get the last figure.

This is all on python 3.5.2 installed by anaconda

**Comment by Phlya** [comment] 2017-04-01 08:03
Hi Mike, would you mind creating a minimal reproducible example?

In general, I suspect that the second plot is actually what happens, and you have to change the parameters to make it look nicer. Very long labels are prone to give strange results... In the latest commit I added separate forces for x and y movement, you probably want to increase the y forces and decrease the x forces.

**Comment by Phlya** [comment] 2017-04-23 09:13
Closing the issue since it's been a while...

**Closed by Phlya** 2017-04-23 09:13 UTC
